application:
  authentication:
    socialProviders: "github"
    socialProvidersConfig:
      gitlab:
        nameCaseParse: false
spring:
  security:
    oauth2:
      client:
        provider:
          gitlab:
            issuer-uri: "https://gitlab.com"
        registration:
          github:
            client-id: "<github-client-id>"
            client-secret: "<github-client-secret>"
          gitlab:
            authorization-grant-type: "authorization_code"
            client-id: "<gitlab-client-id>"
            client-secret: "<gitlab-client-secret>"
            redirect-uri: "http://localhost:8080/login/oauth2/code/gitlab"
            scope: "read_user,openid,profile,email"
