application:
  authentication:
    socialProviders: 'github'
    socialProvidersConfig:
      gitlab:
        nameCaseParse: false
spring:
  security:
    oauth2:
      client:
        provider:
          gitlab:
            issuer-uri: 'https://gitlab.com'
            # Required for OAuth2. Default discovered "user-info-uri" endpoint not working (HTTP 403), so we override it with API user info endpoint
            # user-info-uri: 'https://gitlab.com/api/v4/user'
            # user-name-attribute: 'username'
        registration:
          github: # GitHub provider already predefined in CommonOAuth2Provider
            client-id: '<github_client_id>'
            client-secret: '<github_client_secret>'
          gitlab:
            authorization-grant-type: 'authorization_code'
            client-id: '<gitlab_client_id>'
            client-secret: '<gitlab_client_secret>'
            redirect-uri: 'http://localhost:8080/login/oauth2/code/gitlab'
            scope: 'read_user,openid,profile,email' # OIDC
            # scope: 'read_user'
