spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    password: "changeme"
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=suricate"
    username: "postgres"
  flyway:
    locations: "classpath:flyway/postgresql"
