ALTER TABLE user MODIFY token VARCHAR(500);
ALTER TABLE user ADD COLUMN firstname VARCHAR(250);
ALTER TABLE user ADD COLUMN lastname VARCHAR(250);
ALTER TABLE user ADD COLUMN email VARCHAR(250);
ALTER TABLE user ADD COLUMN password VARCHAR(250);
ALTER TABLE user ADD COLUMN auth_mode VARCHAR(20) NOT NULL;