create table asset (id bigint not null auto_increment, content LONGBLOB, content_type varchar(100), last_update_date datetime, size bigint, primary key (id));
create table category (id bigint not null auto_increment, name varchar(255) not null, technical_name varchar(255) not null, image_id bigint, primary key (id));
create table configuration (config_key varchar(255) not null, config_export bit, config_value varchar(255) not null, primary key (config_key));
create table library (id bigint not null auto_increment, technical_name varchar(255) not null, asset_id bigint, primary key (id));
create table project (id bigint not null auto_increment, max_column integer, name varchar(255) not null, token varchar(255) not null, widget_height integer, primary key (id));
create table project_widget (id bigint not null auto_increment, backend_config longtext, col integer, custom_style longtext, data longtext, height integer, last_execution_date datetime, last_success_date datetime, log longtext, row integer, state varchar(255), width integer, project_id bigint, widget_id bigint, primary key (id));
create table role (id bigint not null auto_increment, description varchar(100) not null, name varchar(50) not null, primary key (id));
create table user (id bigint not null auto_increment, token varchar(255) not null, username varchar(255) not null, primary key (id));
create table user_project (project_id bigint not null, user_id bigint not null);
create table user_role (user_id bigint not null, role_id bigint not null);
create table widget (id bigint not null auto_increment, backend_js longtext, css_content longtext, delay bigint, description varchar(255) not null, html_content longtext, info varchar(255), name varchar(255) not null, technical_name varchar(255), widget_availability varchar(255), category_id bigint, image_id bigint, primary key (id));
create table widget_library (widget_id bigint not null, library_id bigint not null);
alter table category add constraint UK_n5gls3480itfbp741mhbfb2d unique (technical_name);
alter table library add constraint UK_pc7safhs6qww5wt5580p0i89w unique (technical_name);
alter table role add constraint UK_8sewwnpamngi6b1dwaa88askk unique (name);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table widget add constraint UK_b8rll6nakgi3r672miiw97au8 unique (technical_name);
alter table category add constraint FK4sgvky38cyb1ta2ryeedfd159 foreign key (image_id) references asset (id);
alter table library add constraint FK6ui5hkf9jbks1nensblpjqt8y foreign key (asset_id) references asset (id);
alter table project_widget add constraint FKfpx6yf34pokxx1uq8t6e5yrvm foreign key (project_id) references project (id);
alter table project_widget add constraint FKnw2lu1272n29bw8kyydtpnjal foreign key (widget_id) references widget (id);
alter table user_project add constraint FKpw81exe7fsdl7mddqujvu91kx foreign key (user_id) references user (id);
alter table user_project add constraint FKocfkr6u2yh3w1qmybs8vxuv1c foreign key (project_id) references project (id);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
alter table widget add constraint FKjvjhmno1tt6vpdgodr85se58q foreign key (category_id) references category (id);
alter table widget add constraint FKoftbcer6l0d4bi2e4kaw2au0x foreign key (image_id) references asset (id);
alter table widget_library add constraint FKegbsjv0ksivgvuh1syknwwigj foreign key (library_id) references library (id);
alter table widget_library add constraint FKkcnfdat90v00aim4bftjhc5yy foreign key (widget_id) references widget (id);