###     Properties for docker env      ###
##########################################

###   DATASOURCES   ###
## You can override datasource by uncommented and fill these lines
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-db:3306/suricate
    driverClassName: com.mysql.jdbc.Driver
    username: demo
    password: demo
  ###   DDL   ###
  jpa.hibernate.ddl-auto: validate

application:
  ### Security (ldap | database) ###
  authentication.provider: database
  ### Widgets Repo ###
  widgets.local.folderPath: