name: Continuous integration

on:
  push:
    branches: [ master ]

jobs:
  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Style
        run: mvn checkstyle:check

      - name: Build
        run: mvn clean package -P production

      - name: Publish test report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'target/surefire-reports/TEST-*.xml'

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ${{ github.workspace }}/target/suricate.jar

      - name: Sonar
        run: mvn verify sonar:sonar -DcentralAnalyzerEnabled=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build
        run: |
          npm install --no-progress
          npm run build -- --configuration production

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test-headless-no-sandbox -- --watch=false --progress=false --code-coverage

  docker:
    runs-on: ubuntu-latest
    needs: [ front-end, back-end ]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker
        run: mvn package -P production -DskipTests jib:build -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_TOKEN
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
