name: GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  GitHub-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Package application & Deploy Docker
        id: package-application
        run: |
          mvn -B -DskipTests package -P production jib:build -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_TOKEN
          echo ::set-output name=tag::${GITHUB_REF##*/}
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Release Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        id: build_changelog
        with:
          configuration: 'changelog-builder.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          artifacts: 'target/suricate.jar'
          name: Release ${{ steps.package-application.outputs.tag }}
          draft: true
          prerelease: true
          allowUpdates: true
